name: gcloud function

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "270.0.0"
          # service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud functions deploy serverless-example \
            --runtime nodejs8 \
            --entry-point run
